apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-config
  namespace: realtime-pricing
data:
  # Kafka
  KAFKA_BROKER: "host.docker.internal:29092"
  KAFKA_TOPIC_TICKS: "price_ticks"
  KAFKA_GROUP_ID: "pipeline-processor"

  # Redis
  REDIS_ADDR: "host.docker.internal:6379"

  # Postgres
  POSTGRES_DSN: "postgres://pricing:pricing@host.docker.internal:5432/pricing?sslmode=disable"

  # API gateway HTTP-adress (anv√§nds av api-gateway)
  HTTP_ADDR: ":8088"
